[12:59] <5baf7d9ad73408ce4fa9c9b2> @anntzer , running the test locally on my linux I get a bunch of  zero division warnings on the failing test, so you might be able to debug locally still
--------------------------------------------------------------------------------------------------
[13:31] <5684304216b6c7089cc0a229> I get a single warning running tests locally but they still pass...
--------------------------------------------------------------------------------------------------
[15:07] <5baf7d9ad73408ce4fa9c9b2> yeah they pass but they probably should not. Unless you do expect to get a zero division in the test, in which case you need to protect the call. the macOS CIs probably use different versions of numpy or scipy so that's why they fail while the others don't
--------------------------------------------------------------------------------------------------
[15:54] <5684304216b6c7089cc0a229> I'll look into it but it would be strange that different versions of numpy are being used
--------------------------------------------------------------------------------------------------
